<?php

/**
 * @file
 * Cavalla module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */


function getBaseUrl() {
  // output: /myproject/index.php
  $currentPath = $_SERVER['PHP_SELF'];
  
  // output: Array ( [dirname] => /myproject [basename] => index.php [extension] => php [filename] => index )
  $pathInfo = pathinfo($currentPath);
  
  // output: localhost
  $hostName = $_SERVER['HTTP_HOST'];
  
  if ($hostName=='localhost'){
    $protocol = 'http://';

  }
  else{
    $protocol = 'https://';
  }
  
  // return: http://localhost/myproject/
  return $protocol.$hostName.$pathInfo['dirname']."/";
    //  return $pathInfo['dirname']."/";

}

