<?php

/**
 * @file
 * cavalla_basic_page module file.
 */

 use Drupal\Core\Routing\RouteMatchInterface;
 use Drupal\paragraphs\Entity\Paragraph;

 /**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function cavalla_basic_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cavalla_basic_page':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

 /**
  * Implements hook_theme().
  * Lets us define our node templates in this module.
  */
 function cavalla_basic_page_theme($existing, $type, $theme, $path) {
   return [
     'node__cavalla_basic_page' => [
       'base hook' => 'node',
     ],
    
     
    ];
 }

 function cavalla_basic_page_preprocess_node(&$variables) {
  /* create a block object */
  $breadcrump_block_object = \Drupal\block\Entity\Block::load('cavalla_breadcrumbs');
  /* creates a renderable array from the block object */
  $variables['breadcrumb'] = \Drupal::entityManager()->getViewBuilder('block')->view($breadcrump_block_object); 

  $variables['node']=$variables['elements']['#node']; 
  $node = $variables['node'];

  $variables['hero_image_hide'] = $node->get('field_cavalla_bp_hero_image_hide')->value;
}

 function cavalla_basic_page_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'cavalla_basic_page');
}

