<?php

/**
 * @file
 * Cavalla_webform module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function cavalla_webform_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cavalla_webform':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme(). Lets us define our paragraphs templates in this module.
 */
function cavalla_webform_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__cavalla_webform' => [
      'base hook' => 'paragraph',
    ],

  ];
}


function cavalla_webform_preprocess(&$variables) {
  $my_form = \Drupal\webform\Entity\Webform::load('contact');
  $output = \Drupal::entityManager()
      ->getViewBuilder('webform')
      ->view($my_form);

      $variables['webform'] = $output;
}

