<?php

/**
 * @file
 * cavalla_product_feed install file.
 */

/**
 *
 */
  function cavalla_product_feed_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'cavalla_product_feed');
   \Drupal::configFactory()->getEditable('field.field.paragraph.cavalla_commerce_product_feed.field_cavalla_pf_taxonomy')->delete();
   \Drupal::configFactory()->getEditable('field.storage.paragraph.field_cavalla_pf_taxonomy')->delete();
}

